dependencies:
  artemis:
    url: github.com/toitware/toit-artemis
    version: ^0.5.0
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.4.0
  supabase:
    url: github.com/toitware/toit-supabase
    version: ^0.1.0
